# Generated by Django 4.2.4 on 2023-08-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=300, verbose_name='наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'справочник',
                'verbose_name_plural': 'справочники',
            },
        ),
        migrations.CreateModel(
            name='RefBookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='версия')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала действия версии')),
                ('ref_book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_books.refbook', verbose_name='идентификатор справочника')),
            ],
            options={
                'verbose_name': 'версия справочника',
                'verbose_name_plural': 'версии справочников',
                'unique_together': {('ref_book_id', 'version'), ('ref_book_id', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='RefBookElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='код элемента')),
                ('value', models.CharField(max_length=300, verbose_name='значение элемента')),
                ('ref_book_version_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ref_books.refbookversion', verbose_name='идентификатор версии справочника')),
            ],
            options={
                'verbose_name': 'элемент справочник',
                'verbose_name_plural': 'элементы справочников',
                'unique_together': {('ref_book_version_id', 'code')},
            },
        ),
    ]
